import 'package:flutter/material.dart';
class Strings {
  Strings._();
  static const PLAN_NAME = 'My Prepaid';
  static const NUMBER = '092787368820';
  static const DATA_BALANCE = 'Data Balance';
  static const LOAD_BALANCE = 'Load Balance';
  static const REMAINING_DATA = '300 MB';
  static const TOTAL_DATA = 'of 12 GB';
  static const VALID_TILL='Valid till 26 Dec';
  static const RECOMMENDED = 'Recommended';
  static const VIEW_ALL = 'View All';
  static const RECOMMENDED_PLAN = 'GoUNLI350';
  static const PLAN_VALIDITY='30 days UNLI to Globe';
  static const FIFTEEN_DAYS_VALIDITY = '15 days UNLI to Globe';
  static const SPECIAL_PROMOS ='Special Promos';
  static const PROMO_NAME ='GoSakto';
  static const PROMO_TITLE ='Create What Matters';
  static const PROMO_SUBTITLE='Promo that’s all you!';
  static const CREATE_YOUR_OWN_PROMO ='Create your own Promo';
  static const ROAMING_PLANS ='Roaming Plans';
  static const PLAN_FOR_FOREIGN_TRIP='Planing for a foreign trip?';
  static const ROAM_WORRY_FREE='Roam worry free!';
  static const EXPLORE_ROAMING= 'Explore Roaming Packs';
  static const LATEST_PROMOS = 'Latest Promos';
  static const SPOTIFY_PREMIUM ='Spotify Premium';
  static const PACKAGE_TITLE='Subscribe for';
  static const PACKAGE_PRICE='P 129.00';
  static const GLOBE_REWARDS='Globe Rewards';
  static const YOUR_REWARD_POINT = 'Your Reward Points';
  static const POINTS = '7250 Pts';
  static const HERE_IS_WHAT='Here is what you can get';
  static const FIND_OUT_MORE='Find Out More';
  static const NUMBER_POINTS = '1000 Pts';
  static const DISCOUNT = 'P 500 OFF';
  static const OFFER = 'on Shoes';
  static const MYSUBSCRIPTIONS = 'My Subscriptions';
  static const SUBSCRIPTIONS_TITLE = 'With remaining 12GB,you can watch 640 min of video';
  static const POPULAR_ON = 'Popular on';
  static const YOU_MIGHT_ALSO_LIKE = 'You might also like';
  static const SUBSCRIPE_FOR = 'Subscribe for';
  static const SUBSCRIPTION_RATE = 'P 129.00';
  static const GLOBE_PLAN ='GoUNLI180';
  static const GLOBE_VALIDITY ='15 days UNLI to Globe';
  static const FACEBOOK_TITLE = 'Facebook Surf';

}